image: Previous Visual Studio 2022

init:
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- echo %APPVEYOR_BUILD_WORKER_CLOUD%

- ps: |
    if ((Test-Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community") -or
     (Test-Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Preview") -or
     (Test-Path "$env:ProgramFiles\Microsoft Visual Studio\2022\Community")) { $env:vs2019_2022 = 'true'; }

test_script:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: get-path
- ps: ./call_cmdlet.ps1 -AzureTenantId $env:Az_TenantId -AzurePassword $env:Az_ClientSecret -AzureSubscriptionId $env:Az_SubscriptionId -AzureAppId $env:Az_AppId


build: off
